import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "@/components/ui/sonner";
import { QueryClient, QueryClientProvider } from 'react-query';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Trip Planner",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={process.env.VITE_GOOGLE_AUTH_CLIENT_ID}>
          <QueryClientProvider client={queryClient}>
            <Navbar />
            <Toaster />
            {children}
          </QueryClientProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
